use datafusion::prelude::SessionContext;

pub fn register(_ctx: &SessionContext) {
    // TODO: Register datetime functions
    // CURRENT_DATE, CURRENT_TIMESTAMP, CURRENT_TIME, CURRENT_DATETIME
    // DATE_ADD, DATE_SUB, DATE_DIFF, DATE_TRUNC
    // FORMAT_DATE, FORMAT_TIMESTAMP, FORMAT_DATETIME, FORMAT_TIME
    // PARSE_DATE, PARSE_TIMESTAMP, PARSE_DATETIME, PARSE_TIME
    // TIMESTAMP_SECONDS, TIMESTAMP_MILLIS, TIMESTAMP_MICROS
    // UNIX_SECONDS, UNIX_MILLIS, UNIX_MICROS, UNIX_DATE
}
